//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaTransportowa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ADMINISTRACJA
    {
        public ADMINISTRACJA()
        {
            this.CENNIK = new HashSet<CENNIK>();
            this.REZERWACJA = new HashSet<REZERWACJA>();
        }
    
        [Key]
        public int ADM_ID { get; set; }
        public Nullable<int> OSO_ID { get; set; }
        public Nullable<int> ADM_WYNAGRODZENIE { get; set; }
        public string ADM_STANOWISKO { get; set; }
        public Nullable<System.DateTime> ADM_ZATRUDNIONY { get; set; }
    
        public virtual OSOBA OSOBA { get; set; }
        public virtual ICollection<CENNIK> CENNIK { get; set; }
        public virtual ICollection<REZERWACJA> REZERWACJA { get; set; }
    }
}
