//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaTransportowa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CENNIK
    {
        public CENNIK()
        {
            this.PRZEJAZD = new HashSet<PRZEJAZD>();
        }
    
        [Key]
        public int CEN_ID { get; set; }
        public Nullable<int> ADM_ID { get; set; }
        public Nullable<double> CEN_KATO_KRK { get; set; }
        public Nullable<double> CEN_JEDEN_PRZYSTANEK { get; set; }
        public Nullable<int> CEN_ULGA_STUDENT { get; set; }
        public Nullable<int> CEN_ULGA_DZIECI { get; set; }
    
        public virtual ADMINISTRACJA ADMINISTRACJA { get; set; }
        public virtual ICollection<PRZEJAZD> PRZEJAZD { get; set; }
    }
}
