//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaTransportowa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class DANE_TELEADRESOWE
    {
        public DANE_TELEADRESOWE()
        {
            this.OSOBA = new HashSet<OSOBA>();
        }
    
        [Key]
        public int DAN_ID { get; set; }
        [Display(Name = "Ulica, nr lokalu")]
        public string DAN_ULICA_NR_LOKALU { get; set; }
        [Display(Name = "Kod pocztowy")]
        [RegularExpression(@"[0-9]{2}-[0-9]{3}", ErrorMessage = "Niepoprawny kod pocztowy (poprawny format to XX-XXX)")]
        public string DAN_KOD_POCZTOWY { get; set; }
        [Display(Name = "Miasto")]
        public string DAN_MIASTO { get; set; }
        [Display(Name = "Telefon"), Required]
        public Nullable<int> DAN_TELEFON { get; set; }
        [Display(Name = "Email"), Required]
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$", ErrorMessage = "Niepoprawny adres email")]
        public string DAN_EMAIL { get; set; }
    
        public virtual ICollection<OSOBA> OSOBA { get; set; }
    }
}
