//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaTransportowa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DODATKOWE_WYPOSAZENIE
    {
        [Key]
        public int DOD_ID { get; set; }
        public Nullable<int> POJ_ID { get; set; }
        public string DOD_NAZWA { get; set; }
        public string DOD_OPIS { get; set; }
        public Nullable<int> DOD_ILOSC { get; set; }
    
        public virtual POJAZD POJAZD { get; set; }
    }
}
