//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaTransportowa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class firmatransportowaEntities : DbContext
    {
        public firmatransportowaEntities()
            : base("name=firmatransportowaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMINISTRACJA> ADMINISTRACJA { get; set; }
        public DbSet<CENNIK> CENNIKI { get; set; }
        public DbSet<DANE_TELEADRESOWE> DANE_TELEADRESOWE { get; set; }
        public DbSet<DODATKOWE_WYPOSAZENIE> DODATKOWE_WYPOSAZENIE { get; set; }
        public DbSet<KIEROWCA> KIEROWCY { get; set; }
        public DbSet<KLIENT> KLIENCI { get; set; }
        public DbSet<NAGRODA> NAGRODY { get; set; }
        public DbSet<OSOBA> OSOBY { get; set; }
        public DbSet<POJAZD> POJAZDY { get; set; }
        public DbSet<PRZEJAZD> PRZEJAZDY { get; set; }
        public DbSet<PRZYSTANEK> PRZYSTANKI { get; set; }
        public DbSet<PRZYSTANKI_NA_TRASIE> PRZYSTANKI_NA_TRASIE { get; set; }
        public DbSet<REZERWACJA> REZERWACJE { get; set; }
        public DbSet<STAN_TECHNICZNY> STAN_TECHNICZNY { get; set; }
    }
}
