//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaTransportowa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class KIEROWCA
    {
        public KIEROWCA()
        {
            this.PRZEJAZD = new HashSet<PRZEJAZD>();
        }
    
        [Key]
        public int KIE_ID { get; set; }
        public Nullable<int> OSO_ID { get; set; }
        public string KIE_UPRAWNIENIA { get; set; }
        public Nullable<System.DateTime> KIE_ZATRUDNIONY { get; set; }
        public Nullable<int> KIE_WYNAGRODZENIE { get; set; }
    
        public virtual OSOBA OSOBA { get; set; }
        public virtual ICollection<PRZEJAZD> PRZEJAZD { get; set; }
    }
}
