//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaTransportowa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class NAGRODA
    {
        public NAGRODA()
        {
            this.KLIENT = new HashSet<KLIENT>();
        }
    
        [Key]
        public int NAG_ID { get; set; }
        public string NAG_NAZWA { get; set; }
        public Nullable<int> NAG_ILOSC_PUNKTOW { get; set; }
    
        public virtual ICollection<KLIENT> KLIENT { get; set; }
    }
}
