//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaTransportowa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class OSOBA
    {
        public OSOBA()
        {
            this.ADMINISTRACJA = new HashSet<ADMINISTRACJA>();
            this.KIEROWCA = new HashSet<KIEROWCA>();
            this.KLIENT = new HashSet<KLIENT>();
        }
    
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int OSO_ID { get; set; }
        public Nullable<int> DAN_ID { get; set; }
        [Display(Name = "Imiê"), Required]
        public string OSO_IMIE { get; set; }
        [Display(Name = "Nazwisko"), Required]
        public string OSO_NAZWISKO { get; set; }
        [Display(Name = "Data Urodzenia"), DataType(DataType.Date)]
        public Nullable<System.DateTime> OSO_URODZONY { get; set; }
        [Required(ErrorMessage = "Proszê podaæ nazwê u¿ytkownika.", AllowEmptyStrings = false)]
        [Display(Name="Login")]
        public string OSO_LOGIN { get; set; }
        [Required(ErrorMessage = "Proszê podaæ has³o.", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [Display(Name = "Has³o")]
        public string OSO_HASLO { get; set; }
    
        public virtual ICollection<ADMINISTRACJA> ADMINISTRACJA { get; set; }
        public virtual DANE_TELEADRESOWE DANE_TELEADRESOWE { get; set; }
        public virtual ICollection<KIEROWCA> KIEROWCA { get; set; }
        public virtual ICollection<KLIENT> KLIENT { get; set; }
    }
}
