//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaTransportowa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class POJAZD
    {
        public POJAZD()
        {
            this.DODATKOWE_WYPOSAZENIE = new HashSet<DODATKOWE_WYPOSAZENIE>();
            this.PRZEJAZD = new HashSet<PRZEJAZD>();
            this.STAN_TECHNICZNY = new HashSet<STAN_TECHNICZNY>();
        }
    
        [Key]
        public int POJ_ID { get; set; }
        public Nullable<int> POJ_IL_MIEJSC { get; set; }
        public string POJ_MARKA { get; set; }
        public Nullable<int> POJ_ROK_PRODUKCJI { get; set; }
        public string POJ_STATUS { get; set; }
    
        public virtual ICollection<DODATKOWE_WYPOSAZENIE> DODATKOWE_WYPOSAZENIE { get; set; }
        public virtual ICollection<PRZEJAZD> PRZEJAZD { get; set; }
        public virtual ICollection<STAN_TECHNICZNY> STAN_TECHNICZNY { get; set; }
    }
}
