//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaTransportowa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PRZEJAZD
    {
        public PRZEJAZD()
        {
            this.PRZYSTANKI_NA_TRASIE = new HashSet<PRZYSTANKI_NA_TRASIE>();
            this.REZERWACJA = new HashSet<REZERWACJA>();
        }
    
        [Key]
        public int PRD_ID { get; set; }
        public Nullable<int> KIE_ID { get; set; }
        public Nullable<int> CEN_ID { get; set; }
        public Nullable<int> POJ_ID { get; set; }
        public Nullable<System.DateTime> PRD_DATA { get; set; }
        public Nullable<int> PRD_KOSZT { get; set; }
    
        public virtual CENNIK CENNIK { get; set; }
        public virtual KIEROWCA KIEROWCA { get; set; }
        public virtual POJAZD POJAZD { get; set; }
        public virtual ICollection<PRZYSTANKI_NA_TRASIE> PRZYSTANKI_NA_TRASIE { get; set; }
        public virtual ICollection<REZERWACJA> REZERWACJA { get; set; }
    }
}
