//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaTransportowa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PRZYSTANKI_NA_TRASIE
    {
        [Key]
        public int PRE_ID { get; set; }
        public Nullable<System.TimeSpan> PRE_ODJAZD { get; set; }
        public Nullable<int> PRK_ID { get; set; }
        public string PRE_KIERUNEK { get; set; }
    
        public virtual PRZYSTANEK PRZYSTANEK { get; set; }
    }
}
