//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaTransportowa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class STAN_TECHNICZNY
    {
        [Key]
        public int STA_ID { get; set; }
        public Nullable<int> POJ_ID { get; set; }
        public string STA_OPIS { get; set; }
        public Nullable<System.DateTime> STA_UAKTUALNIONO { get; set; }
    
        public virtual POJAZD POJAZD { get; set; }
    }
}
